---
name: "Simple Github Actions workflow"
on:
  push:
    branches:
      - main
      - master
      - production

jobs:

  myjob:

    runs-on: ubuntu-24.04

    steps: 

    - name: "Running Date Command"
      run: date
      shell: bash

    - name: "Getting OS details"
      run: cat /etc/os-release
      shell: bash

    - name: "Current user name"
      run: whoami
      shell: bash

    - name: "Working Directory Details before checkout"
      run: |
        pwd
        ls -la

    - name: "Checkout Current Repository"
      uses: actions/checkout@v4

    - name: "Working directory Details after checkout"
      run: |
        pwd
        ls -la
    - name: "Installing Terraform"
      run: |
        wget https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
        unzip terraform_1.12.2_linux_amd64.zip
        ./terraform version

    - name: "Running script.sh"
      run: 
        chmod +x script.sh
        ./script.sh

